<?php 
    use douggonsouza\routes\router;
    use douggonsouza\gentelela\assets\assets;
?>
    <!-- Bootstrap -->
    <link href="<?= router::assets("/gentelela/vendors/bootstrap/dist/css/bootstrap.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?= router::assets("/gentelela/vendors/font-awesome/css/font-awesome.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?= router::assets("/gentelela/vendors/nprogress/nprogress.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- iCheck -->
    <link href="<?= router::assets("/gentelela/vendors/iCheck/skins/flat/green.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- bootstrap-wysiwyg -->
	<link href="<?= router::assets("/gentelela/vendors/google-code-prettify/bin/prettify.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    	<!-- Select2 -->
	<link href="<?= router::assets("/gentelela/vendors/select2/dist/css/select2.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
	<!-- Switchery -->
	<link href="<?= router::assets("/gentelela/vendors/switchery/dist/switchery.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
	<!-- starrr -->
	<link href="<?= router::assets("/gentelela/vendors/starrr/dist/starrr.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="<?= router::assets("/gentelela/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- JQVMap -->
    <link href="<?= router::assets("/gentelela/vendors/jqvmap/dist/jqvmap.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet"/>
    <!-- bootstrap-daterangepicker -->
    <link href="<?= router::assets("/gentelela/vendors/bootstrap-daterangepicker/daterangepicker.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">
    <!-- Animate.css -->
    <link href="<?= router::assets("/gentelela/vendors/animate.css/animate.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?= router::assets("/gentelela/build/css/custom.min.css", assets::ABSOLUTE_URL) ?>" rel="stylesheet">