<?php 
    use douggonsouza\routes\router;
    use douggonsouza\gentelela\assets\assets;
?>
    <!-- jQuery -->
    <script src="<?= router::assets("/gentelela/vendors/jquery/dist/jquery.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- Bootstrap -->
    <script src="<?= router::assets("/gentelela/vendors/bootstrap/dist/js/bootstrap.bundle.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- FastClick -->
    <script src="<?= router::assets("/gentelela/vendors/fastclick/lib/fastclick.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- NProgress -->
    <script src="<?= router::assets("/gentelela/vendors/nprogress/nprogress.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- Chart.js -->
    <script src="<?= router::assets("/gentelela/vendors/Chart.js/dist/Chart.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- gauge.js -->
    <script src="<?= router::assets("/gentelela/vendors/gauge.js/dist/gauge.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- bootstrap-progressbar -->
    <script src="<?= router::assets("/gentelela/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- iCheck -->
    <script src="<?= router::assets("/gentelela/vendors/iCheck/icheck.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- Skycons -->
    <script src="<?= router::assets("/gentelela/vendors/skycons/skycons.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- bootstrap-wysiwyg -->
	<script src="<?= router::assets("/gentelela/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<script src="<?= router::assets("/gentelela/vendors/jquery.hotkeys/jquery.hotkeys.js", assets::ABSOLUTE_URL) ?>"></script>
	<script src="<?= router::assets("/gentelela/vendors/google-code-prettify/src/prettify.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- jQuery Tags Input -->
	<script src="<?= router::assets("/gentelela/vendors/jquery.tagsinput/src/jquery.tagsinput.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- Switchery -->
	<script src="<?= router::assets("/gentelela/vendors/switchery/dist/switchery.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- Select2 -->
	<script src="<?= router::assets("/gentelela/vendors/select2/dist/js/select2.full.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- Parsley -->
	<script src="<?= router::assets("/gentelela/vendors/parsleyjs/dist/parsley.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- Autosize -->
	<script src="<?= router::assets("/gentelela/vendors/autosize/dist/autosize.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- jQuery autocomplete -->
	<script src="<?= router::assets("/gentelela/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js", assets::ABSOLUTE_URL) ?>"></script>
	<!-- starrr -->
	<script src="<?= router::assets("/gentelela/vendors/starrr/dist/starrr.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- Flot -->
    <script src="<?= router::assets("/gentelela/vendors/Flot/jquery.flot.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/Flot/jquery.flot.pie.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/Flot/jquery.flot.time.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/Flot/jquery.flot.stack.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/Flot/jquery.flot.resize.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- Flot plugins -->
    <script src="<?= router::assets("/gentelela/vendors/flot.orderbars/js/jquery.flot.orderBars.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/flot-spline/js/jquery.flot.spline.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/flot.curvedlines/curvedLines.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- DateJS -->
    <script src="<?= router::assets("/gentelela/vendors/DateJS/build/date.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- JQVMap -->
    <script src="<?= router::assets("/gentelela/vendors/jqvmap/dist/jquery.vmap.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/jqvmap/dist/maps/jquery.vmap.world.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js", assets::ABSOLUTE_URL) ?>"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="<?= router::assets("/gentelela/vendors/moment/min/moment.min.js", assets::ABSOLUTE_URL) ?>"></script>
    <script src="<?= router::assets("/gentelela/vendors/bootstrap-daterangepicker/daterangepicker.js", assets::ABSOLUTE_URL) ?>"></script>

    <!-- Custom Theme Scripts -->
    <script src="<?= router::assets("/gentelela/build/js/custom.min.js", assets::ABSOLUTE_URL) ?>"></script>
