<?php 
    use douggonsouza\routes\router;
    use douggonsouza\gentelela\assets\assets;
    use douggonsouza\mvc\control\controllers;
?>
            <form>
              <h1>Login Form</h1>
              <div>
                <input type="text" class="form-control" placeholder="Username" required="" />
              </div>
              <div>
                <input type="password" class="form-control" placeholder="Password" required="" />
              </div>
              <div>
                <a class="btn btn-default submit" href="<?= router::label('#'); ?>">Log in</a>
                <a class="reset_pass" href="<?= router::label('#'); ?>">Lost your password?</a>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">New to site?
                  <a href="<?= router::label('#signup'); ?>" class="to_register"> Create Account </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>

                  <!-- DISCOVERY START BLOCK : COPYRIGHT -->

                  <?php
                      router::part(new controllers(COPYRIGHT));
                  ?>
                
                  <!-- DISCOVERY END BLOCK -->

                </div>
              </div>
            </form>