<?php 
    use douggonsouza\routes\router;
    use douggonsouza\gentelela\assets\assets;
?>
    <!-- jQuery -->
    <script src="<?= router::assets("/gentelela/vendors/jquery/dist/jquery.min.js", assets::ABSOLUTE_URL) ?>" ></script>
    <!-- Bootstrap -->
   <script src="<?= router::assets("/gentelela/vendors/bootstrap/dist/js/bootstrap.bundle.min.js", assets::ABSOLUTE_URL) ?>" ></script>
    <!-- FastClick -->
    <script src="<?= router::assets("/gentelela/vendors/fastclick/lib/fastclick.js", assets::ABSOLUTE_URL) ?>" ></script>
    <!-- NProgress -->
    <script src="<?= router::assets("/gentelela/vendors/nprogress/nprogress.js", assets::ABSOLUTE_URL) ?>" ></script>
    
    <!-- Custom Theme Scripts -->
    <script src="<?= router::assets("/gentelela/build/js/custom.min.js", assets::ABSOLUTE_URL) ?>" ></script>
