<?php 
    use douggonsouza\routes\router;
    use douggonsouza\mvc\control\controllers;
?>
<!DOCTYPE html>
<html lang="pt-br">
  <head>

    <!-- DISCOVERY START BLOCK : LOGIN_HEAD -->

    <?php
        router::part(new controllers(LOGIN_HEAD));
    ?>

    <!-- DISCOVERY END BLOCK -->

    <!-- DISCOVERY START BLOCK : LOGIN_CSS -->

    <?php
        router::part(new controllers(LOGIN_CSS));
    ?>

    <!-- DISCOVERY END BLOCK -->
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

      <div class="login_wrapper">
        <div class="animate form login_form">
          <section class="login_content">

            <!-- DISCOVERY START BLOCK : LOGIN_LOGIN_CONTENT -->

            <?php
                router::part(new controllers(LOGIN_LOGIN_CONTENT));
            ?>

            <!-- DISCOVERY END BLOCK -->

          </section>
        </div>

        <div id="register" class="animate form registration_form">
          <section class="login_content">

            <!-- DISCOVERY START BLOCK : LOGIN_REGISTER_CONTENT -->

            <?php
                router::part(new controllers(LOGIN_REGISTER_CONTENT));
            ?>

            <!-- DISCOVERY END BLOCK -->

          </section>
        </div>
      </div>
    </div>
  </body>
</html>
